# Generated by Django 4.2.4 on 2023-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('method', models.CharField(max_length=100)),
                ('consult', models.CharField(max_length=1000)),
                ('dataReturn', models.CharField(max_length=1000)),
            ],
        ),
    ]
